### ISSUE TITLE
Conseguir o modelo do fórmula SAE CIMATEC

### ISSUE THREAD

**Issue by FelipeArtur** [FelipeArtur/VRSAE-Simulator#12]
- [x] Entrar em contato com a equipe do fórmula SAE CIMATEC
- [x] Identificar a extensão suportada pelo **Unreal Engine 4.27**
- [ ] Definir o melhor modelo para o projeto

**Comment by rafaelmiguez** [comment]
- [ ] analisar o que exatamente tem que ter o modelo da formula SAE
